---
- name: install epel-release
  yum: name=epel-release state=present
- name: install python
  yum: name=python2-pip state=present
- name: install docker
  yum: name=docker state=present
- name: install docker-py
  command: pip install docker-py
